/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInviteRouteImport } from './routes/_app/invite'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdAnalyticsRouteImport } from './routes/_app/projects/$projectId/analytics'
import { Route as AppProjectsProjectIdIntegrationsRouteImport } from './routes/_app/projects/$projectId/integrations'
import { Route as AppProjectsProjectIdMembersRouteImport } from './routes/_app/projects/$projectId/members'
import { Route as AppProjectsProjectIdStoresRouteImport } from './routes/_app/projects/$projectId/stores'
import { Route as AppProjectsProjectIdOnboardingsIndexRouteImport } from './routes/_app/projects/$projectId/onboardings/index'
import { Route as AppProjectsProjectIdOnboardingsOnboardingIdRouteImport } from './routes/_app/projects/$projectId/onboardings/$onboardingId'
import { Route as AppProjectsProjectIdStoresIndexRouteImport } from './routes/_app/projects/$projectId/stores/index'
import { Route as AppProjectsProjectIdStoresReleasesRouteImport } from './routes/_app/projects/$projectId/stores/releases'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInviteRoute = AppInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdAnalyticsRoute =
  AppProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdIntegrationsRoute =
  AppProjectsProjectIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdMembersRoute =
  AppProjectsProjectIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdStoresRoute =
  AppProjectsProjectIdStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdOnboardingsIndexRoute =
  AppProjectsProjectIdOnboardingsIndexRouteImport.update({
    id: '/onboardings/',
    path: '/onboardings/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdOnboardingsOnboardingIdRoute =
  AppProjectsProjectIdOnboardingsOnboardingIdRouteImport.update({
    id: '/onboardings/$onboardingId',
    path: '/onboardings/$onboardingId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdStoresIndexRoute =
  AppProjectsProjectIdStoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdStoresRoute,
  } as any)
const AppProjectsProjectIdStoresReleasesRoute =
  AppProjectsProjectIdStoresReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AppProjectsProjectIdStoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/invite': typeof AppInviteRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/integrations': typeof AppProjectsProjectIdIntegrationsRoute
  '/projects/$projectId/members': typeof AppProjectsProjectIdMembersRoute
  '/projects/$projectId/stores': typeof AppProjectsProjectIdStoresRouteWithChildren
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/onboardings/$onboardingId': typeof AppProjectsProjectIdOnboardingsOnboardingIdRoute
  '/projects/$projectId/stores/releases': typeof AppProjectsProjectIdStoresReleasesRoute
  '/projects/$projectId/onboardings/': typeof AppProjectsProjectIdOnboardingsIndexRoute
  '/projects/$projectId/stores/': typeof AppProjectsProjectIdStoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/invite': typeof AppInviteRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/projects/$projectId/integrations': typeof AppProjectsProjectIdIntegrationsRoute
  '/projects/$projectId/members': typeof AppProjectsProjectIdMembersRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/onboardings/$onboardingId': typeof AppProjectsProjectIdOnboardingsOnboardingIdRoute
  '/projects/$projectId/stores/releases': typeof AppProjectsProjectIdStoresReleasesRoute
  '/projects/$projectId/onboardings': typeof AppProjectsProjectIdOnboardingsIndexRoute
  '/projects/$projectId/stores': typeof AppProjectsProjectIdStoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/invite': typeof AppInviteRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/_app/projects/$projectId/integrations': typeof AppProjectsProjectIdIntegrationsRoute
  '/_app/projects/$projectId/members': typeof AppProjectsProjectIdMembersRoute
  '/_app/projects/$projectId/stores': typeof AppProjectsProjectIdStoresRouteWithChildren
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/onboardings/$onboardingId': typeof AppProjectsProjectIdOnboardingsOnboardingIdRoute
  '/_app/projects/$projectId/stores/releases': typeof AppProjectsProjectIdStoresReleasesRoute
  '/_app/projects/$projectId/onboardings/': typeof AppProjectsProjectIdOnboardingsIndexRoute
  '/_app/projects/$projectId/stores/': typeof AppProjectsProjectIdStoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/projects/$projectId'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/integrations'
    | '/projects/$projectId/members'
    | '/projects/$projectId/stores'
    | '/projects/$projectId/'
    | '/projects/$projectId/onboardings/$onboardingId'
    | '/projects/$projectId/stores/releases'
    | '/projects/$projectId/onboardings/'
    | '/projects/$projectId/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/projects/$projectId/analytics'
    | '/projects/$projectId/integrations'
    | '/projects/$projectId/members'
    | '/projects/$projectId'
    | '/projects/$projectId/onboardings/$onboardingId'
    | '/projects/$projectId/stores/releases'
    | '/projects/$projectId/onboardings'
    | '/projects/$projectId/stores'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/invite'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_app/'
    | '/_app/projects/$projectId'
    | '/_app/projects/$projectId/analytics'
    | '/_app/projects/$projectId/integrations'
    | '/_app/projects/$projectId/members'
    | '/_app/projects/$projectId/stores'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/onboardings/$onboardingId'
    | '/_app/projects/$projectId/stores/releases'
    | '/_app/projects/$projectId/onboardings/'
    | '/_app/projects/$projectId/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invite': {
      id: '/_app/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AppInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/analytics': {
      id: '/_app/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/projects/$projectId/analytics'
      preLoaderRoute: typeof AppProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/integrations': {
      id: '/_app/projects/$projectId/integrations'
      path: '/integrations'
      fullPath: '/projects/$projectId/integrations'
      preLoaderRoute: typeof AppProjectsProjectIdIntegrationsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/members': {
      id: '/_app/projects/$projectId/members'
      path: '/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof AppProjectsProjectIdMembersRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/stores': {
      id: '/_app/projects/$projectId/stores'
      path: '/stores'
      fullPath: '/projects/$projectId/stores'
      preLoaderRoute: typeof AppProjectsProjectIdStoresRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/onboardings/': {
      id: '/_app/projects/$projectId/onboardings/'
      path: '/onboardings'
      fullPath: '/projects/$projectId/onboardings/'
      preLoaderRoute: typeof AppProjectsProjectIdOnboardingsIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/onboardings/$onboardingId': {
      id: '/_app/projects/$projectId/onboardings/$onboardingId'
      path: '/onboardings/$onboardingId'
      fullPath: '/projects/$projectId/onboardings/$onboardingId'
      preLoaderRoute: typeof AppProjectsProjectIdOnboardingsOnboardingIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/stores/': {
      id: '/_app/projects/$projectId/stores/'
      path: '/'
      fullPath: '/projects/$projectId/stores/'
      preLoaderRoute: typeof AppProjectsProjectIdStoresIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdStoresRoute
    }
    '/_app/projects/$projectId/stores/releases': {
      id: '/_app/projects/$projectId/stores/releases'
      path: '/releases'
      fullPath: '/projects/$projectId/stores/releases'
      preLoaderRoute: typeof AppProjectsProjectIdStoresReleasesRouteImport
      parentRoute: typeof AppProjectsProjectIdStoresRoute
    }
  }
}

interface AppProjectsProjectIdStoresRouteChildren {
  AppProjectsProjectIdStoresReleasesRoute: typeof AppProjectsProjectIdStoresReleasesRoute
  AppProjectsProjectIdStoresIndexRoute: typeof AppProjectsProjectIdStoresIndexRoute
}

const AppProjectsProjectIdStoresRouteChildren: AppProjectsProjectIdStoresRouteChildren =
  {
    AppProjectsProjectIdStoresReleasesRoute:
      AppProjectsProjectIdStoresReleasesRoute,
    AppProjectsProjectIdStoresIndexRoute: AppProjectsProjectIdStoresIndexRoute,
  }

const AppProjectsProjectIdStoresRouteWithChildren =
  AppProjectsProjectIdStoresRoute._addFileChildren(
    AppProjectsProjectIdStoresRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdAnalyticsRoute: typeof AppProjectsProjectIdAnalyticsRoute
  AppProjectsProjectIdIntegrationsRoute: typeof AppProjectsProjectIdIntegrationsRoute
  AppProjectsProjectIdMembersRoute: typeof AppProjectsProjectIdMembersRoute
  AppProjectsProjectIdStoresRoute: typeof AppProjectsProjectIdStoresRouteWithChildren
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdOnboardingsOnboardingIdRoute: typeof AppProjectsProjectIdOnboardingsOnboardingIdRoute
  AppProjectsProjectIdOnboardingsIndexRoute: typeof AppProjectsProjectIdOnboardingsIndexRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdAnalyticsRoute: AppProjectsProjectIdAnalyticsRoute,
  AppProjectsProjectIdIntegrationsRoute: AppProjectsProjectIdIntegrationsRoute,
  AppProjectsProjectIdMembersRoute: AppProjectsProjectIdMembersRoute,
  AppProjectsProjectIdStoresRoute: AppProjectsProjectIdStoresRouteWithChildren,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdOnboardingsOnboardingIdRoute:
    AppProjectsProjectIdOnboardingsOnboardingIdRoute,
  AppProjectsProjectIdOnboardingsIndexRoute:
    AppProjectsProjectIdOnboardingsIndexRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppInviteRoute: typeof AppInviteRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppInviteRoute: AppInviteRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
